/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  date?: string;
  startTime?: string;
  endTime?: string;
  location?: {
    name?: string;
    address?: string;
    mapUrl?: string;
  };
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  links?: Array<{
    title?: string;
    url?: string;
    _type: "eventLink";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Event
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../bitclubvt.org/src/sanity/lib/queries.ts
// Variable: EVENT_SLUGS_QUERY
// Query: *[    _type == "event" &&    defined(slug.current) &&    defined(date) &&    defined(startTime) &&    defined(endTime)  ] | order(slug.current asc) {    "slug": slug.current  }
export type EVENT_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: ../bitclubvt.org/src/sanity/lib/queries.ts
// Variable: ALL_EVENTS_QUERY
// Query: *[    _type == "event" &&    defined(slug.current) &&    defined(date) &&    defined(startTime) &&    defined(endTime)  ] | order(date asc, startTime asc, _id asc) {    _id,    name,    "slug": slug.current,    date,    startTime,    endTime,    location {      name,      address,      mapUrl    },    image {      _type,      alt,      crop,      hotspot,      asset->{        _id,        url,        metadata {          lqip,          dimensions {            width,            height,            aspectRatio          }        }      }    }  }
export type ALL_EVENTS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  date: string | null;
  startTime: string | null;
  endTime: string | null;
  location: {
    name: string | null;
    address: string | null;
    mapUrl: string | null;
  } | null;
  image: {
    _type: "image";
    alt: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
  } | null;
}>;

// Source: ../bitclubvt.org/src/sanity/lib/queries.ts
// Variable: EVENT_QUERY
// Query: *[_type == "event" && slug.current == $slug][0] {    _id,    name,    "slug": slug.current,    date,    startTime,    endTime,    location {      name,      address,      mapUrl    },    image {      _type,      alt,      crop,      hotspot,      asset->{        _id,        url,        metadata {          lqip,          dimensions {            width,            height,            aspectRatio          }        }      }    },    description,    links[]{      _key,      title,      url    }  }
export type EVENT_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: string | null;
  date: string | null;
  startTime: string | null;
  endTime: string | null;
  location: {
    name: string | null;
    address: string | null;
    mapUrl: string | null;
  } | null;
  image: {
    _type: "image";
    alt: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    asset: {
      _id: string;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
      } | null;
    } | null;
  } | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h2" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  links: Array<{
    _key: string;
    title: string | null;
    url: string | null;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[\n    _type == "event" &&\n    defined(slug.current) &&\n    defined(date) &&\n    defined(startTime) &&\n    defined(endTime)\n  ] | order(slug.current asc) {\n    "slug": slug.current\n  }\n': EVENT_SLUGS_QUERY_RESULT;
    '\n  *[\n    _type == "event" &&\n    defined(slug.current) &&\n    defined(date) &&\n    defined(startTime) &&\n    defined(endTime)\n  ] | order(date asc, startTime asc, _id asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    date,\n    startTime,\n    endTime,\n    location {\n      name,\n      address,\n      mapUrl\n    },\n    image {\n      _type,\n      alt,\n      crop,\n      hotspot,\n      asset->{\n        _id,\n        url,\n        metadata {\n          lqip,\n          dimensions {\n            width,\n            height,\n            aspectRatio\n          }\n        }\n      }\n    }\n  }\n': ALL_EVENTS_QUERY_RESULT;
    '\n  *[_type == "event" && slug.current == $slug][0] {\n    _id,\n    name,\n    "slug": slug.current,\n    date,\n    startTime,\n    endTime,\n    location {\n      name,\n      address,\n      mapUrl\n    },\n    image {\n      _type,\n      alt,\n      crop,\n      hotspot,\n      asset->{\n        _id,\n        url,\n        metadata {\n          lqip,\n          dimensions {\n            width,\n            height,\n            aspectRatio\n          }\n        }\n      }\n    },\n    description,\n    links[]{\n      _key,\n      title,\n      url\n    }\n  }\n': EVENT_QUERY_RESULT;
  }
}
